config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'about', to: 'personal#about'
  get 'resume', to: 'personal#resume'
  get 'home', to: 'home#index'
  get 'tools', to: 'tools#index'

  namespace :tools do
    namespace :core_keeper do
      get 'stat_calculator', to: 'stat_calculator#index'
    end
  end

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
require 'active_page_finder'

class ApplicationController < ActionController::Base
  before_action :set_active_page

  def set_active_page
    active_page_finder = ActivePageFinder.new(params)
    @active_page = active_page_finder.find
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/personal_controller.rb
# frozen_string_literal: true

class PersonalController < ApplicationController
  def about; end

  def resume; end
end

app/controllers/tools/core_keeper/stat_calculator_controller.rb
# frozen_string_literal: true

module Tools
  module CoreKeeper
    class StatCalculatorController < ApplicationController
      def index; end
    end
  end
end

app/controllers/tools_controller.rb
# frozen_string_literal: true

class ToolsController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def active_class_for_page(page)
    @active_page == page ? 'active' : ''
  end
  
  def external_link_image_tag
    image_tag 'arrow-up-right-from-square-solid.svg', class: 'link-icon', width: '20', height: '20',
                                                      alt: 'external link'
  end

  def here_image_tag
    image_tag 'arrow-left-long-solid.svg', class: 'here-icon', width: '20', height: '20', alt: 'left arrow'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/personal_helper.rb
module PersonalHelper
end

app/helpers/tools/core_keeper/stat_calculator_helper.rb
module Tools::CoreKeeper::StatCalculatorHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/home/index.html.erb
<h2>Micah's World</h2>
<p>Welcome to my subsection of brain delivered in a cyberspace.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Micah's World</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="theme-neon-space">
    <header>
      <%= render "shared/projects_nav" %>
    </header>

    <main>
      <h1 class="primary-heading">Micah's</h1>

      <article id="content">
        <%= yield %>
      </article>
    </main>

    <div id="mobile-nav-background"></div>

    <footer>
      <%= render "shared/personal_nav" %>
    </footer>
  </body>
</html>

app/views/personal/about.html.erb
<h2>About Me</h2>

<p>
  I'm a software engineer working primarily with Ruby and JavaScript. I have professional experience in start-ups and
  non-profits, where I develop and advocate for accessible, ethical, and pleasant software for the users and developers
  alike.
</p>

<p>
  Outside of software, I'm in a loving partnership with my best friend, Sean, and our two non-human kids, Ziggy and
  Hazel.
</p>

<h3>Resume</h3>
Looking for my resume or more info on my professional experience? Check out my
<%= link_to 'https://www.linkedin.com/in/myka-micah/' do %><%= external_link_image_tag %> LinkedIn! <% end %>

app/views/personal/resume.html.erb
<h2>Resume</h2>
<p>Find me in app/views/personal/resume.html.erb</p>

app/views/shared/_personal_nav.html.erb
<nav aria-labelledby="personal-header">
  <h2 id="personal-header" class="primary-heading">
    Personals
  </h2>

  <ul>
    <li class=<%= active_class_for_page('about') %>>
      <%= link_to about_path do %>
        About
        <% if @active_page == 'about' %>
          <span class="here">
            (Here)
          </span>
        <% end %>
      <% end %>
    </li>
    <li>
      My Accounts

      <ul class="sub-nav">
        <li>
          <%= link_to 'https://www.linkedin.com/in/myka-micah/' do %>
            <%= external_link_image_tag %> LinkedIn
          <% end %>
        </li>
        <li>
          <%= link_to 'https://github.com/timefreer' do %>
            <%= external_link_image_tag %> Github
          <% end %>
        </li>
        <li>
          <%= link_to 'https://fosstodon.org/@timefreer' do %>
            <%= external_link_image_tag %> Mastodon
          <% end %>
        </li>
        <li>
          <%= link_to 'https://steamcommunity.com/profiles/76561198064671958/' do %>
            <%= external_link_image_tag %> Steam
          <% end %>
        </li>
      </ul>
    </li>
  </ul>
</nav>

app/views/shared/_projects_nav.html.erb
<nav aria-labelledby="projects-header">
  <h2 id="projects-header" class="primary-heading">
    Projects
  </h2>

  <ul>
    <li>
      <%= link_to tools_path do %>
        Tools
        <% if @active_page == 'tools' %>
          <span class="here">
            (Here)
          </span>
        <% end %>
      <% end %>
    </li>
  </ul>
</nav>

app/views/tools/core_keeper/stat_calculator/index.html.erb
<h2>Stat Calculator</h2>

app/views/tools/index.html.erb
<h2>Toolin' Around</h2>

<figure>
  <q>Tool me once, shame on you. Tool me twice, still shame on you.</q>
  <figcaption>
    <cite>Micah - 2023</cite>
  </figcaption>
</figure>

<p>
  Tools coming soon!
</p>

<!--<h3>Core Keeper</h3>-->
<!--<ul>-->
<!--  <li><%#= link_to 'DPS Calculator', tools_core_keeper_stat_calculator_path  %></li>-->
<!--</ul>-->